### ISSUE TITLE
Скрипт снова рушится из-за отсутствия рута

### ISSUE THREAD

**Issue by Lapparrr** [PheeZz/wireguard-bot#10]
![image](https://github.com/PheeZz/wireguard-bot/assets/62951378/223065ca-0dd2-400a-9b6e-f73a47d619cf)
В процессе выполнения скрипта все сломалось из-за отсутствия доступа

**Comment by PheeZz** [comment]
Здравствуйте, попробуйте заменить строки 179-183 в скрипте для установки на
```
#create wg keys
sudo wg genkey | sudo tee /etc/wireguard/privatekey | sudo wg pubkey | sudo tee /etc/wireguard/publickey
sudo wg genpsk | sudo tee /etc/wireguard/presharedkey
sudo chmod 600 /etc/wireguard/privatekey
sudo chmod 600 /etc/wireguard/presharedkey
```
если это исправит ситуацию - опубликую изменения

**Comment by Lapparrr** [comment]
еще пару замечаний мелких
https://github.com/PheeZz/wireguard-bot/blob/56faec16883e1f8bb8281f24e862736192bc6894/SemiAutoInstall.sh#L157C1-L158C56
Это я бы добавил в блок if а то получается что-то такое 
![image](https://github.com/PheeZz/wireguard-bot/assets/62951378/b41d6948-b254-4dd2-b1a0-ea94f0b3ab21)
и уменьшил таймер с 500 секунд до 5
https://github.com/PheeZz/wireguard-bot/blob/56faec16883e1f8bb8281f24e862736192bc6894/SemiAutoInstall.sh#L160
