### ISSUE TITLE
rewrites ip wg to 10.0.0.1

### ISSUE THREAD

**Issue by dimkulik** [PheeZz/wireguard-bot#15]
During installation I set a completely different ip, but then it’s still rewritten to 10.0.0.1

help me fix this

**Comment by PheeZz** [comment]
What IP are you talking about? If you are talking about DNS, then if you have chosen to install AdGuard - the DNS IP address will be 10.0.0.1, as this is the only place where AdGuard will operate

**Comment by dimkulik** [comment]
> О каком IP речь? Если вы говорите о DNS, то если вы выбрали установку AdGuard - IP-адрес DNS будет 10.0.0.1, так как это единственное место, где будет работать AdGuard.

I didn't install adguar. in this file (etc/wireguard/wg0.conf) when installing the bot I specify 10.0.10.1, but after the user receives the config, the bot stops working and in the wg0.conf file the address changes to 10.0.0.1

As they told me in technical support, the server itself runs on the same IP (10.0.0.1) and I need to change it so that there are no failures

I’m writing through Google Translator, since English is not my native language.

**Comment by PheeZz** [comment]
Адрес `10.0.0.1` действительно является зарезервированным и указывает непосредственно на сам сервер и не может использоваться для пиров. Вы запускаете скрипт для установки от root пользователя? Не совсем понимаю для какого параметра вы пытаетесь установить значение `10.0.10.1`.  Если ошибка возникает после автоматической установки - попробуйте ручную, все необходимые шаги прописаны в [Readme.md](https://github.com/PheeZz/wireguard-bot/blob/master/README.md).
