### ISSUE TITLE
 не работает база данных

### ISSUE THREAD

**Issue by Danilrrrr** [PheeZz/wireguard-bot#3]
Добрый день, у вас отличный бот, выражаю огромную благодарность за проделанную работу!

у меня при установке бота возникла пара проблем,  я уверен что проблема на моей стороне но все же может быть Вы можете мне помочь

1. при формировании базы данных я получаю вот такую ошибку postgres could not change directory to ....

2. если опустить выше перечисленную ошибку я так и не смог разобраться как через бота подтвердить оплату

**Comment by Danilrrrr** [comment]
подозреваю что вся проблема в базе данных так как у клиента не получается посмотреть дату истечении подписке и вприципе конфиг не создается

**Comment by PheeZz** [comment]
Добрый день, с первой проблемой, увы, я помочь не могу, смею предположить, что проблема вызвана правами доступа пользователя Linux при попытке установки\настройки PostgreSql.
По подтверждению оплаты: при нажатии на кнопку "оплатить" пользователь должен самостоятельно оформить банковский перевод и выслать боту скриншот, подтверждающий оплату. Полученное изображение переадресовывается администратору(-ам), указанным в конфиге вместе с telegram user id пользователя и его username. После проверки оплаты администратор может выдать пользователю доступ на указанный период
(прямо в чате с ботом) `/give <telegram user id> <int days>`, например `/give 123456 30` выдаст пользователю с telegram id 123456 30 дней доступа к сервису.

**Comment by Danilrrrr** [comment]
Спасибо Вам большое 
буду разбираться с Postresql

Успехов Вам!
