### ISSUE TITLE
опять вопрос по базе данных(

### ISSUE THREAD

**Issue by Danilrrrr** [PheeZz/wireguard-bot#4]
Подскажите а база данных должна создаваться в этом же каталоге где и бот?

**Comment by PheeZz** [comment]
Нет, в обычном сценарии она размещается в `/var/lib/pgsql/data`

[Документация PostgreSQL](https://postgrespro.ru/docs/postgresql/9.6/storage-file-layout#:~:text=%D0%9E%D0%B1%D1%8B%D1%87%D0%BD%D0%BE%20PGDATA%20%D0%BD%D0%B0%D1%85%D0%BE%D0%B4%D0%B8%D1%82%D1%81%D1%8F%20%D0%B2%20%2Fvar%2Flib%2Fpgsql%2Fdata%20.)

**Comment by Danilrrrr** [comment]
Да, у меня была проблема из-за того что я разместил бота в каталоге /root, из-за этого база не могла подключиться. Когда я разместил базу в каталоге /home все заработало 🙂
