### ISSUE TITLE
PresharedKey

### ISSUE THREAD

**Issue by reinethernal** [PheeZz/wireguard-bot#6]
При заполнении конфига возникает вопрос - откуда брать этот ключ?

**Comment by reinethernal** [comment]
Ну и можно ли его не использовать?

**Comment by PheeZz** [comment]
1. `wg genpsk` - выводит в терминал сгенерированный preshared key
2. можно не использовать, но в таком случае нужно переписать логику создания клиентских и серверной конфигураций в модуле `utils/vpn_cfg_work.py`

**Comment by reinethernal** [comment]
1. И от этого ключа он будет генерировать клиентские? 
2. Т.е если я выпилю допустим в этом файле строку 166 - оно ж не положит весь остальной конфиг?)))

**Comment by reinethernal** [comment]
Вот ещё в догонку вопрос. Права на wg0.conf должны быть какими? 644 хватит? Я к тому что почему-то конфиг не дописывается

**Comment by PheeZz** [comment]
1. этот ключ будет общим и для клиента и для сервера
2. Существующие конфиги, прописанные вручную - нет, новые, сгенерированные ботом - да, поскольку 166 строка отвечает только за пользовательский конфиг

**Comment by PheeZz** [comment]
с правами не игрался, по умолчанию стоят 644, в нормальных условиях этого достаточно, если код запускается из под рута\пользователя имеющего доступ к записи в файл

**Comment by reinethernal** [comment]
> с правами не игрался, по умолчанию стоят 644, в нормальных условиях этого достаточно, если код запускается из под рута\пользователя имеющего доступ к записи в файл

Вот в том-то и загвоздка. Новые не дописываются. Почему - понять не могу. Может подскажете куда копать? 

ubuntu 22.04
python 3.6.10

**Comment by PheeZz** [comment]
Уважаемый, перечитайте, пожалуйста README, в частности раздел [Stack](https://github.com/PheeZz/wireguard-bot#stack)
Как минимум ошибка в том, что необходимо использовать версию python 3.10+ для запуска проекта.

**Comment by reinethernal** [comment]
Ввёл в вас в заблуждение.
![image](https://github.com/PheeZz/wireguard-bot/assets/35932698/318abefb-3e7e-4517-ad1b-2b55ea3ce762)
И кстати, можно закрывать. Ребутнул хост - все заработало. Спасибо!
