### ISSUE TITLE
Скрипт рушится на данных строчках при запуске не от рут пользователя

### ISSUE THREAD

**Issue by alexsyw** [PheeZz/wireguard-bot#9]
![Termius_ztIak4b7Yc](https://github.com/PheeZz/wireguard-bot/assets/33035109/888a1d64-03b7-4f0d-bf21-8b87a8c74d71)
https://github.com/PheeZz/wireguard-bot/blob/4fea2a2c7e3e258384b0591fe306590f288fd954/SemiAutoInstall.sh#L180-L181

решение: запуск данных команд с sudo привилегиями

**Comment by PheeZz** [comment]
Подскажите, а на какой ОС вы запускаете скрипт? Ubuntu 20.02 и 22.04 данной проблемы не показывали.

**Comment by alexsyw** [comment]
на ubuntu 22.04

**Comment by PheeZz** [comment]
Странно, ладно, спасибо в любом случае за фидбек, изменения внес.👍🏽

**Comment by alexsyw** [comment]
в этих строчках тоже, возможно, не срабатывание скрипта
https://github.com/PheeZz/wireguard-bot/blob/4fea2a2c7e3e258384b0591fe306590f288fd954/SemiAutoInstall.sh#L228-L229
